name: autoblack
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Black
        run: pip install black

      - name: Run black check on solo
        run: black --check --line-length 100 solo
      
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black --line-length 100 solo
          git config --global user.name 'autoblack'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: format solo with Black"
          git push
      
      - name: Run black --check on tests
        run: black --check --line-length 100 tests
      
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black --line-length 100 tests
          git config --global user.name 'autoblack'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: format tests with Black"
          git push